# Generated by Django 3.0.6 on 2020-07-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_fname', models.CharField(max_length=64)),
                ('author_sname', models.CharField(max_length=64)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_pass', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_context', models.TextField()),
                ('blog_date', models.DateField(auto_now=True)),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Authors')),
            ],
        ),
    ]
