# Generated by Django 3.0.6 on 2020-07-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
